import type { SidebarDocument, SidebarItem } from "./sidebar.js";

/** A documentation page referenced by its Content Collections slug. */
export type PrestigiaSidebarSlugItem = {
  /** Override the document title used as the link label. */
  label?: string;
  /** Content Collections path without a leading slash or file extension. */
  slug: string;
};

/** A navigation link that is not backed by a documentation document. */
export type PrestigiaSidebarLinkItem = {
  /** Visible link label. */
  label: string;
  /** Internal route or external URL. */
  link: string;
};

/** Generate navigation for every document below a content directory. */
export type PrestigiaSidebarAutogenerateItem = {
  autogenerate: {
    /** Directory relative to the documentation collection root. */
    directory: string;
    /** Collapse nested generated directory groups initially. */
    collapsed?: boolean;
  };
  /** Wrap generated links in a labelled group. */
  label?: string;
  /** Collapse the optional labelled wrapper initially. */
  collapsed?: boolean;
};

/** A recursively nested group of configured sidebar entries. */
export type PrestigiaSidebarGroupItem = {
  /** Collapse this group initially. */
  collapsed?: boolean;
  /** Child links, groups, or autogenerated entries. */
  items: ReadonlyArray<PrestigiaSidebarConfigItem>;
  /** Visible group label. */
  label: string;
};

/** One Starlight-style entry in `prestigia.config.ts`. */
export type PrestigiaSidebarConfigItem =
  | string
  | PrestigiaSidebarAutogenerateItem
  | PrestigiaSidebarGroupItem
  | PrestigiaSidebarLinkItem
  | PrestigiaSidebarSlugItem;

/** Serializable application configuration loaded by the Prestigia plugin. */
export interface PrestigiaConfig {
  /** Authored navigation merged with Content Collections documents. */
  sidebar?: ReadonlyArray<PrestigiaSidebarConfigItem>;
  /** Additional serializable Prestigia settings. */
  readonly [key: string]: unknown;
}

/** Configuration exposed by `virtual:prestigia/config`. */
export interface ResolvedPrestigiaConfig {
  /** Navigation with document titles and URLs resolved. */
  sidebar: ReadonlyArray<SidebarItem>;
  readonly [key: string]: unknown;
}

export interface ResolvePrestigiaSidebarOptions {
  /** URL prefix placed before documentation slugs. */
  basePath?: string;
}

type GeneratedGroup = {
  children: Map<string, GeneratedGroup>;
  documents: Array<{ document: SidebarDocument; segment: string }>;
};

function normalizePath(value: string): string {
  return value.replace(/^\/+|\/+$/gu, "");
}

function getDocumentSlug(document: SidebarDocument): string {
  return normalizePath(
    "slug" in document ? document.slug : document._meta.path,
  );
}

function documentHref(basePath: string, slug: string): string {
  return `/${[normalizePath(basePath), normalizePath(slug)]
    .filter(Boolean)
    .join("/")}`;
}

function createGeneratedGroup(): GeneratedGroup {
  return { children: new Map(), documents: [] };
}

function generatedItems(
  documents: ReadonlyArray<SidebarDocument>,
  directory: string,
  basePath: string,
  collapsed?: boolean,
): Array<SidebarItem> {
  const normalizedDirectory = normalizePath(directory);
  const prefix = normalizedDirectory ? `${normalizedDirectory}/` : "";
  const root = createGeneratedGroup();

  const matchingDocuments = documents
    .filter((document) => getDocumentSlug(document).startsWith(prefix))
    .sort((left, right) =>
      getDocumentSlug(left).localeCompare(getDocumentSlug(right)),
    );

  for (const document of matchingDocuments) {
    const relativeSlug = getDocumentSlug(document).slice(prefix.length);
    const segments = relativeSlug.split("/");
    let group = root;

    for (const segment of segments.slice(0, -1)) {
      let child = group.children.get(segment);

      if (!child) {
        child = createGeneratedGroup();
        group.children.set(segment, child);
      }

      group = child;
    }

    group.documents.push({
      document,
      segment: segments.at(-1) ?? relativeSlug,
    });
  }

  function toSidebarItems(group: GeneratedGroup): Array<SidebarItem> {
    const links = group.documents.map(({ document, segment }) => {
      const slug = getDocumentSlug(document);

      return {
        sortKey: segment,
        item: {
          type: "link" as const,
          label: document.title,
          href: documentHref(basePath, slug),
        },
      };
    });
    const groups = [...group.children.entries()].map(([label, child]) => ({
      sortKey: label,
      item: {
        type: "group" as const,
        label,
        collapsed,
        items: toSidebarItems(child),
      },
    }));

    return [...links, ...groups]
      .sort((left, right) => left.sortKey.localeCompare(right.sortKey))
      .map(({ item }) => item);
  }

  return toSidebarItems(root);
}

/**
 * Merge Starlight-style sidebar configuration with Content Collections data.
 * Document-backed entries inherit their labels from the matching document.
 */
export function resolvePrestigiaSidebar(
  documents: ReadonlyArray<SidebarDocument>,
  sidebar?: ReadonlyArray<PrestigiaSidebarConfigItem>,
  { basePath = "/docs" }: ResolvePrestigiaSidebarOptions = {},
): Array<SidebarItem> {
  if (!sidebar) return generatedItems(documents, "", basePath);

  const documentsBySlug = new Map(
    documents.map((document) => [getDocumentSlug(document), document]),
  );

  function resolveItems(
    entries: ReadonlyArray<PrestigiaSidebarConfigItem>,
  ): Array<SidebarItem> {
    return entries.flatMap((entry): Array<SidebarItem> => {
      if (typeof entry === "string" || "slug" in entry) {
        const slug = normalizePath(
          typeof entry === "string" ? entry : entry.slug,
        );
        const document = documentsBySlug.get(slug);

        if (!document) {
          throw new Error(
            `Prestigia sidebar references an unknown document slug: ${slug}`,
          );
        }

        return [
          {
            type: "link",
            label:
              typeof entry === "string"
                ? document.title
                : (entry.label ?? document.title),
            href: documentHref(basePath, slug),
          },
        ];
      }

      if ("link" in entry) {
        return [{ type: "link", label: entry.label, href: entry.link }];
      }

      if ("items" in entry) {
        return [
          {
            type: "group",
            label: entry.label,
            collapsed: entry.collapsed,
            items: resolveItems(entry.items),
          },
        ];
      }

      const items = generatedItems(
        documents,
        entry.autogenerate.directory,
        basePath,
        entry.autogenerate.collapsed,
      );

      return entry.label
        ? [
            {
              type: "group",
              label: entry.label,
              collapsed: entry.collapsed,
              items,
            },
          ]
        : items;
    });
  }

  return resolveItems(sidebar);
}
