/* This file is generated by Prestige plugin and it is read-only. Do not modify it */
import { createLazyFileRoute } from "@tanstack/react-router";
import * as contentData from "virtual:prestige/content/docs/reference/plugin-reference";
import { LazyContentRoute } from "@lonik/prestige/ui";

export const Route = createLazyFileRoute('/(prestige)/docs/reference/plugin-reference')(LazyContentRoute(contentData));
