/* This file is generated by Prestige plugin and it is read-only. Do not modify it */
import { createFileRoute } from "@tanstack/react-router";
import * as contentData from "virtual:prestige/content/docs/guides/prestige-shell";
import { ContentRoute } from "@lonik/prestige/ui";

export const Route = createFileRoute('/(prestige)/docs/guides/prestige-shell')(ContentRoute(contentData));
