/* This file is generated by Prestige plugin and it is read-only. Do not modify it */
import { createLazyFileRoute } from "@tanstack/react-router";
import * as contentData from "virtual:prestige/content/docs/reference/create-prestige-reference";
import { LazyContentRoute } from "@lonik/prestige/ui";

export const Route = createLazyFileRoute('/(prestige)/docs/reference/create-prestige-reference')(LazyContentRoute(contentData));
