packages:
  - packages/*
  - apps/*

catalog:
  '@semantic-release/exec': ^7.1.0
  '@semantic-release/git': ^10.0.1
  '@tailwindcss/typography': ^0.5.19
  '@tailwindcss/vite': ^4.2.1
  '@tanstack/react-devtools': 0.9.6
  '@tanstack/react-router': ^1.162.4
  '@tanstack/react-router-devtools': 1.162.4
  '@tanstack/react-start': ^1.162.4
  '@types/node': ^25.0.3
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.4
  bumpp: ^10.4.1
  lucide-react: ^0.545.0
  nitro: 3.0.1-alpha.2
  pathe: ^2.0.3
  react: ^19.2.0
  react-dom: ^19.2.0
  semantic-release: ^25.0.3
  tailwindcss: ^4.2.1
  tsdown: ^0.18.1
  typescript: ^5.9.3
  vite: ^7.3.1
  vite-tsconfig-paths: ^6.1.1
  vitest: ^4.0.16

cleanupUnusedCatalogs: true

linkWorkspacePackages: true

preferWorkspacePackages: true
