packages:
  - packages/*
  - apps/*

catalog:
  '@semantic-release/exec': ^7.1.0
  '@semantic-release/git': ^11.0.1
  '@tailwindcss/typography': ^0.5.20
  '@tailwindcss/vite': ^4.3.3
  '@tanstack/query-core': ^5.102.8
  '@tanstack/react-devtools': 0.10.12
  '@tanstack/react-query': ^5.102.8
  '@tanstack/react-router': ^1.170.32
  '@tanstack/react-router-devtools': 1.167.1
  '@tanstack/react-start': ^1.168.49
  '@types/node': ^26.4.0
  '@types/react': ^19.2.18
  '@types/react-dom': ^19.2.5
  '@vitejs/plugin-react': ^6.1.1
  bumpp: ^12.2.2
  lucide-react: ^1.35.0
  pathe: ^2.0.3
  react: ^19.2.8
  react-dom: ^19.2.8
  semantic-release: ^25.0.9
  tailwindcss: ^4.3.3
  tsdown: ^0.22.14
  typescript: ^7.0.2
  vite: ^8.2.2
  vitest: ^4.1.11

cleanupUnusedCatalogs: true

linkWorkspacePackages: true

preferWorkspacePackages: true

allowBuilds:
  esbuild: true
  lightningcss: true

minimumReleaseAgeExclude:
  - electron-to-chromium
  - lucide-react
  - pretty-ms
  - zod
