cleanupUnusedCatalogs: true
linkWorkspacePackages: true
preferWorkspacePackages: true

packages:
  - packages/*

catalog:
  "@arethetypeswrong/cli": ^0.18.5
  "@changesets/changelog-github": ^1.0.0
  "@changesets/cli": ^3.0.1
  "@tanstack/eslint-config": ^0.4.0
  "@types/node": ^26.4.0
  eslint: ^10.9.1
  nx: 23.1.2
  pkg-pr-new: 0.0.88
  premove: ^4.0.0
  prettier: ^3.9.6
  publint: ^0.3.24
  tsdown: ^0.22.14
  typescript: 6.0.2
  vitest: ^4.1.11

allowBuilds:
  nx: true
  unrs-resolver: false
