/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as prestigeDocsIntroductionRouteImport } from './routes/(prestige)/docs.introduction'
import { Route as prestigeDocsGettingStartedRouteImport } from './routes/(prestige)/docs.getting-started'
import { Route as prestigeDocsReferencePrestigeShellReferenceRouteImport } from './routes/(prestige)/docs.reference.prestige-shell-reference'
import { Route as prestigeDocsReferencePluginReferenceRouteImport } from './routes/(prestige)/docs.reference.plugin-reference'
import { Route as prestigeDocsReferenceFrontmatterReferenceRouteImport } from './routes/(prestige)/docs.reference.frontmatter-reference'
import { Route as prestigeDocsReferenceCreatePrestigeReferenceRouteImport } from './routes/(prestige)/docs.reference.create-prestige-reference'
import { Route as prestigeDocsGuidesVitePluginRouteImport } from './routes/(prestige)/docs.guides.vite-plugin'
import { Route as prestigeDocsGuidesPrestigeShellRouteImport } from './routes/(prestige)/docs.guides.prestige-shell'
import { Route as prestigeDocsGuidesPageRouteImport } from './routes/(prestige)/docs.guides.page'
import { Route as prestigeDocsGuidesOverviewRouteImport } from './routes/(prestige)/docs.guides.overview'
import { Route as prestigeDocsGuidesCollectionRouteImport } from './routes/(prestige)/docs.guides.collection'

const prestigeDocsLazyRouteImport = createFileRoute('/(prestige)/docs')()

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const prestigeDocsLazyRoute = prestigeDocsLazyRouteImport
  .update({
    id: '/(prestige)/docs',
    path: '/docs',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(prestige)/docs.lazy').then((d) => d.Route))
const prestigeDocsIntroductionRoute = prestigeDocsIntroductionRouteImport
  .update({
    id: '/introduction',
    path: '/introduction',
    getParentRoute: () => prestigeDocsLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/docs.introduction.lazy').then((d) => d.Route),
  )
const prestigeDocsGettingStartedRoute = prestigeDocsGettingStartedRouteImport
  .update({
    id: '/getting-started',
    path: '/getting-started',
    getParentRoute: () => prestigeDocsLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/docs.getting-started.lazy').then(
      (d) => d.Route,
    ),
  )
const prestigeDocsReferencePrestigeShellReferenceRoute =
  prestigeDocsReferencePrestigeShellReferenceRouteImport
    .update({
      id: '/reference/prestige-shell-reference',
      path: '/reference/prestige-shell-reference',
      getParentRoute: () => prestigeDocsLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/docs.reference.prestige-shell-reference.lazy').then(
        (d) => d.Route,
      ),
    )
const prestigeDocsReferencePluginReferenceRoute =
  prestigeDocsReferencePluginReferenceRouteImport
    .update({
      id: '/reference/plugin-reference',
      path: '/reference/plugin-reference',
      getParentRoute: () => prestigeDocsLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/docs.reference.plugin-reference.lazy').then(
        (d) => d.Route,
      ),
    )
const prestigeDocsReferenceFrontmatterReferenceRoute =
  prestigeDocsReferenceFrontmatterReferenceRouteImport
    .update({
      id: '/reference/frontmatter-reference',
      path: '/reference/frontmatter-reference',
      getParentRoute: () => prestigeDocsLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/docs.reference.frontmatter-reference.lazy').then(
        (d) => d.Route,
      ),
    )
const prestigeDocsReferenceCreatePrestigeReferenceRoute =
  prestigeDocsReferenceCreatePrestigeReferenceRouteImport
    .update({
      id: '/reference/create-prestige-reference',
      path: '/reference/create-prestige-reference',
      getParentRoute: () => prestigeDocsLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/docs.reference.create-prestige-reference.lazy').then(
        (d) => d.Route,
      ),
    )
const prestigeDocsGuidesVitePluginRoute =
  prestigeDocsGuidesVitePluginRouteImport
    .update({
      id: '/guides/vite-plugin',
      path: '/guides/vite-plugin',
      getParentRoute: () => prestigeDocsLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/docs.guides.vite-plugin.lazy').then(
        (d) => d.Route,
      ),
    )
const prestigeDocsGuidesPrestigeShellRoute =
  prestigeDocsGuidesPrestigeShellRouteImport
    .update({
      id: '/guides/prestige-shell',
      path: '/guides/prestige-shell',
      getParentRoute: () => prestigeDocsLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/docs.guides.prestige-shell.lazy').then(
        (d) => d.Route,
      ),
    )
const prestigeDocsGuidesPageRoute = prestigeDocsGuidesPageRouteImport
  .update({
    id: '/guides/page',
    path: '/guides/page',
    getParentRoute: () => prestigeDocsLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/docs.guides.page.lazy').then((d) => d.Route),
  )
const prestigeDocsGuidesOverviewRoute = prestigeDocsGuidesOverviewRouteImport
  .update({
    id: '/guides/overview',
    path: '/guides/overview',
    getParentRoute: () => prestigeDocsLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/docs.guides.overview.lazy').then(
      (d) => d.Route,
    ),
  )
const prestigeDocsGuidesCollectionRoute =
  prestigeDocsGuidesCollectionRouteImport
    .update({
      id: '/guides/collection',
      path: '/guides/collection',
      getParentRoute: () => prestigeDocsLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/docs.guides.collection.lazy').then(
        (d) => d.Route,
      ),
    )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof prestigeDocsLazyRouteWithChildren
  '/docs/getting-started': typeof prestigeDocsGettingStartedRoute
  '/docs/introduction': typeof prestigeDocsIntroductionRoute
  '/docs/guides/collection': typeof prestigeDocsGuidesCollectionRoute
  '/docs/guides/overview': typeof prestigeDocsGuidesOverviewRoute
  '/docs/guides/page': typeof prestigeDocsGuidesPageRoute
  '/docs/guides/prestige-shell': typeof prestigeDocsGuidesPrestigeShellRoute
  '/docs/guides/vite-plugin': typeof prestigeDocsGuidesVitePluginRoute
  '/docs/reference/create-prestige-reference': typeof prestigeDocsReferenceCreatePrestigeReferenceRoute
  '/docs/reference/frontmatter-reference': typeof prestigeDocsReferenceFrontmatterReferenceRoute
  '/docs/reference/plugin-reference': typeof prestigeDocsReferencePluginReferenceRoute
  '/docs/reference/prestige-shell-reference': typeof prestigeDocsReferencePrestigeShellReferenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof prestigeDocsLazyRouteWithChildren
  '/docs/getting-started': typeof prestigeDocsGettingStartedRoute
  '/docs/introduction': typeof prestigeDocsIntroductionRoute
  '/docs/guides/collection': typeof prestigeDocsGuidesCollectionRoute
  '/docs/guides/overview': typeof prestigeDocsGuidesOverviewRoute
  '/docs/guides/page': typeof prestigeDocsGuidesPageRoute
  '/docs/guides/prestige-shell': typeof prestigeDocsGuidesPrestigeShellRoute
  '/docs/guides/vite-plugin': typeof prestigeDocsGuidesVitePluginRoute
  '/docs/reference/create-prestige-reference': typeof prestigeDocsReferenceCreatePrestigeReferenceRoute
  '/docs/reference/frontmatter-reference': typeof prestigeDocsReferenceFrontmatterReferenceRoute
  '/docs/reference/plugin-reference': typeof prestigeDocsReferencePluginReferenceRoute
  '/docs/reference/prestige-shell-reference': typeof prestigeDocsReferencePrestigeShellReferenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/(prestige)/docs': typeof prestigeDocsLazyRouteWithChildren
  '/(prestige)/docs/getting-started': typeof prestigeDocsGettingStartedRoute
  '/(prestige)/docs/introduction': typeof prestigeDocsIntroductionRoute
  '/(prestige)/docs/guides/collection': typeof prestigeDocsGuidesCollectionRoute
  '/(prestige)/docs/guides/overview': typeof prestigeDocsGuidesOverviewRoute
  '/(prestige)/docs/guides/page': typeof prestigeDocsGuidesPageRoute
  '/(prestige)/docs/guides/prestige-shell': typeof prestigeDocsGuidesPrestigeShellRoute
  '/(prestige)/docs/guides/vite-plugin': typeof prestigeDocsGuidesVitePluginRoute
  '/(prestige)/docs/reference/create-prestige-reference': typeof prestigeDocsReferenceCreatePrestigeReferenceRoute
  '/(prestige)/docs/reference/frontmatter-reference': typeof prestigeDocsReferenceFrontmatterReferenceRoute
  '/(prestige)/docs/reference/plugin-reference': typeof prestigeDocsReferencePluginReferenceRoute
  '/(prestige)/docs/reference/prestige-shell-reference': typeof prestigeDocsReferencePrestigeShellReferenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/docs'
    | '/docs/getting-started'
    | '/docs/introduction'
    | '/docs/guides/collection'
    | '/docs/guides/overview'
    | '/docs/guides/page'
    | '/docs/guides/prestige-shell'
    | '/docs/guides/vite-plugin'
    | '/docs/reference/create-prestige-reference'
    | '/docs/reference/frontmatter-reference'
    | '/docs/reference/plugin-reference'
    | '/docs/reference/prestige-shell-reference'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/docs'
    | '/docs/getting-started'
    | '/docs/introduction'
    | '/docs/guides/collection'
    | '/docs/guides/overview'
    | '/docs/guides/page'
    | '/docs/guides/prestige-shell'
    | '/docs/guides/vite-plugin'
    | '/docs/reference/create-prestige-reference'
    | '/docs/reference/frontmatter-reference'
    | '/docs/reference/plugin-reference'
    | '/docs/reference/prestige-shell-reference'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/(prestige)/docs'
    | '/(prestige)/docs/getting-started'
    | '/(prestige)/docs/introduction'
    | '/(prestige)/docs/guides/collection'
    | '/(prestige)/docs/guides/overview'
    | '/(prestige)/docs/guides/page'
    | '/(prestige)/docs/guides/prestige-shell'
    | '/(prestige)/docs/guides/vite-plugin'
    | '/(prestige)/docs/reference/create-prestige-reference'
    | '/(prestige)/docs/reference/frontmatter-reference'
    | '/(prestige)/docs/reference/plugin-reference'
    | '/(prestige)/docs/reference/prestige-shell-reference'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  prestigeDocsLazyRoute: typeof prestigeDocsLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(prestige)/docs': {
      id: '/(prestige)/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof prestigeDocsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(prestige)/docs/introduction': {
      id: '/(prestige)/docs/introduction'
      path: '/introduction'
      fullPath: '/docs/introduction'
      preLoaderRoute: typeof prestigeDocsIntroductionRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/getting-started': {
      id: '/(prestige)/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof prestigeDocsGettingStartedRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/reference/prestige-shell-reference': {
      id: '/(prestige)/docs/reference/prestige-shell-reference'
      path: '/reference/prestige-shell-reference'
      fullPath: '/docs/reference/prestige-shell-reference'
      preLoaderRoute: typeof prestigeDocsReferencePrestigeShellReferenceRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/reference/plugin-reference': {
      id: '/(prestige)/docs/reference/plugin-reference'
      path: '/reference/plugin-reference'
      fullPath: '/docs/reference/plugin-reference'
      preLoaderRoute: typeof prestigeDocsReferencePluginReferenceRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/reference/frontmatter-reference': {
      id: '/(prestige)/docs/reference/frontmatter-reference'
      path: '/reference/frontmatter-reference'
      fullPath: '/docs/reference/frontmatter-reference'
      preLoaderRoute: typeof prestigeDocsReferenceFrontmatterReferenceRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/reference/create-prestige-reference': {
      id: '/(prestige)/docs/reference/create-prestige-reference'
      path: '/reference/create-prestige-reference'
      fullPath: '/docs/reference/create-prestige-reference'
      preLoaderRoute: typeof prestigeDocsReferenceCreatePrestigeReferenceRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/guides/vite-plugin': {
      id: '/(prestige)/docs/guides/vite-plugin'
      path: '/guides/vite-plugin'
      fullPath: '/docs/guides/vite-plugin'
      preLoaderRoute: typeof prestigeDocsGuidesVitePluginRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/guides/prestige-shell': {
      id: '/(prestige)/docs/guides/prestige-shell'
      path: '/guides/prestige-shell'
      fullPath: '/docs/guides/prestige-shell'
      preLoaderRoute: typeof prestigeDocsGuidesPrestigeShellRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/guides/page': {
      id: '/(prestige)/docs/guides/page'
      path: '/guides/page'
      fullPath: '/docs/guides/page'
      preLoaderRoute: typeof prestigeDocsGuidesPageRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/guides/overview': {
      id: '/(prestige)/docs/guides/overview'
      path: '/guides/overview'
      fullPath: '/docs/guides/overview'
      preLoaderRoute: typeof prestigeDocsGuidesOverviewRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/guides/collection': {
      id: '/(prestige)/docs/guides/collection'
      path: '/guides/collection'
      fullPath: '/docs/guides/collection'
      preLoaderRoute: typeof prestigeDocsGuidesCollectionRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
  }
}

interface prestigeDocsLazyRouteChildren {
  prestigeDocsGettingStartedRoute: typeof prestigeDocsGettingStartedRoute
  prestigeDocsIntroductionRoute: typeof prestigeDocsIntroductionRoute
  prestigeDocsGuidesCollectionRoute: typeof prestigeDocsGuidesCollectionRoute
  prestigeDocsGuidesOverviewRoute: typeof prestigeDocsGuidesOverviewRoute
  prestigeDocsGuidesPageRoute: typeof prestigeDocsGuidesPageRoute
  prestigeDocsGuidesPrestigeShellRoute: typeof prestigeDocsGuidesPrestigeShellRoute
  prestigeDocsGuidesVitePluginRoute: typeof prestigeDocsGuidesVitePluginRoute
  prestigeDocsReferenceCreatePrestigeReferenceRoute: typeof prestigeDocsReferenceCreatePrestigeReferenceRoute
  prestigeDocsReferenceFrontmatterReferenceRoute: typeof prestigeDocsReferenceFrontmatterReferenceRoute
  prestigeDocsReferencePluginReferenceRoute: typeof prestigeDocsReferencePluginReferenceRoute
  prestigeDocsReferencePrestigeShellReferenceRoute: typeof prestigeDocsReferencePrestigeShellReferenceRoute
}

const prestigeDocsLazyRouteChildren: prestigeDocsLazyRouteChildren = {
  prestigeDocsGettingStartedRoute: prestigeDocsGettingStartedRoute,
  prestigeDocsIntroductionRoute: prestigeDocsIntroductionRoute,
  prestigeDocsGuidesCollectionRoute: prestigeDocsGuidesCollectionRoute,
  prestigeDocsGuidesOverviewRoute: prestigeDocsGuidesOverviewRoute,
  prestigeDocsGuidesPageRoute: prestigeDocsGuidesPageRoute,
  prestigeDocsGuidesPrestigeShellRoute: prestigeDocsGuidesPrestigeShellRoute,
  prestigeDocsGuidesVitePluginRoute: prestigeDocsGuidesVitePluginRoute,
  prestigeDocsReferenceCreatePrestigeReferenceRoute:
    prestigeDocsReferenceCreatePrestigeReferenceRoute,
  prestigeDocsReferenceFrontmatterReferenceRoute:
    prestigeDocsReferenceFrontmatterReferenceRoute,
  prestigeDocsReferencePluginReferenceRoute:
    prestigeDocsReferencePluginReferenceRoute,
  prestigeDocsReferencePrestigeShellReferenceRoute:
    prestigeDocsReferencePrestigeShellReferenceRoute,
}

const prestigeDocsLazyRouteWithChildren =
  prestigeDocsLazyRoute._addFileChildren(prestigeDocsLazyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  prestigeDocsLazyRoute: prestigeDocsLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
