/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as prestigeDocsIntroductionRouteImport } from './routes/(prestige)/docs.introduction'
import { Route as prestigeDocsGettingStartedRouteImport } from './routes/(prestige)/docs.getting-started'
import { Route as prestigeDocsReferencePluginReferenceRouteImport } from './routes/(prestige)/docs.reference.plugin-reference'
import { Route as prestigeDocsReferenceFrontmatterReferenceRouteImport } from './routes/(prestige)/docs.reference.frontmatter-reference'
import { Route as prestigeDocsGuidesPagesRouteImport } from './routes/(prestige)/docs.guides.pages'
import { Route as prestigeDocsGuidesCollectionsRouteImport } from './routes/(prestige)/docs.guides.collections'

const prestigeDocsLazyRouteImport = createFileRoute('/(prestige)/docs')()

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const prestigeDocsLazyRoute = prestigeDocsLazyRouteImport
  .update({
    id: '/(prestige)/docs',
    path: '/docs',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(prestige)/docs.lazy').then((d) => d.Route))
const prestigeDocsIntroductionRoute = prestigeDocsIntroductionRouteImport
  .update({
    id: '/introduction',
    path: '/introduction',
    getParentRoute: () => prestigeDocsLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/docs.introduction.lazy').then((d) => d.Route),
  )
const prestigeDocsGettingStartedRoute = prestigeDocsGettingStartedRouteImport
  .update({
    id: '/getting-started',
    path: '/getting-started',
    getParentRoute: () => prestigeDocsLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/docs.getting-started.lazy').then(
      (d) => d.Route,
    ),
  )
const prestigeDocsReferencePluginReferenceRoute =
  prestigeDocsReferencePluginReferenceRouteImport
    .update({
      id: '/reference/plugin-reference',
      path: '/reference/plugin-reference',
      getParentRoute: () => prestigeDocsLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/docs.reference.plugin-reference.lazy').then(
        (d) => d.Route,
      ),
    )
const prestigeDocsReferenceFrontmatterReferenceRoute =
  prestigeDocsReferenceFrontmatterReferenceRouteImport
    .update({
      id: '/reference/frontmatter-reference',
      path: '/reference/frontmatter-reference',
      getParentRoute: () => prestigeDocsLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/docs.reference.frontmatter-reference.lazy').then(
        (d) => d.Route,
      ),
    )
const prestigeDocsGuidesPagesRoute = prestigeDocsGuidesPagesRouteImport
  .update({
    id: '/guides/pages',
    path: '/guides/pages',
    getParentRoute: () => prestigeDocsLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/docs.guides.pages.lazy').then((d) => d.Route),
  )
const prestigeDocsGuidesCollectionsRoute =
  prestigeDocsGuidesCollectionsRouteImport
    .update({
      id: '/guides/collections',
      path: '/guides/collections',
      getParentRoute: () => prestigeDocsLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/docs.guides.collections.lazy').then(
        (d) => d.Route,
      ),
    )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof prestigeDocsLazyRouteWithChildren
  '/docs/getting-started': typeof prestigeDocsGettingStartedRoute
  '/docs/introduction': typeof prestigeDocsIntroductionRoute
  '/docs/guides/collections': typeof prestigeDocsGuidesCollectionsRoute
  '/docs/guides/pages': typeof prestigeDocsGuidesPagesRoute
  '/docs/reference/frontmatter-reference': typeof prestigeDocsReferenceFrontmatterReferenceRoute
  '/docs/reference/plugin-reference': typeof prestigeDocsReferencePluginReferenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof prestigeDocsLazyRouteWithChildren
  '/docs/getting-started': typeof prestigeDocsGettingStartedRoute
  '/docs/introduction': typeof prestigeDocsIntroductionRoute
  '/docs/guides/collections': typeof prestigeDocsGuidesCollectionsRoute
  '/docs/guides/pages': typeof prestigeDocsGuidesPagesRoute
  '/docs/reference/frontmatter-reference': typeof prestigeDocsReferenceFrontmatterReferenceRoute
  '/docs/reference/plugin-reference': typeof prestigeDocsReferencePluginReferenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/(prestige)/docs': typeof prestigeDocsLazyRouteWithChildren
  '/(prestige)/docs/getting-started': typeof prestigeDocsGettingStartedRoute
  '/(prestige)/docs/introduction': typeof prestigeDocsIntroductionRoute
  '/(prestige)/docs/guides/collections': typeof prestigeDocsGuidesCollectionsRoute
  '/(prestige)/docs/guides/pages': typeof prestigeDocsGuidesPagesRoute
  '/(prestige)/docs/reference/frontmatter-reference': typeof prestigeDocsReferenceFrontmatterReferenceRoute
  '/(prestige)/docs/reference/plugin-reference': typeof prestigeDocsReferencePluginReferenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/docs'
    | '/docs/getting-started'
    | '/docs/introduction'
    | '/docs/guides/collections'
    | '/docs/guides/pages'
    | '/docs/reference/frontmatter-reference'
    | '/docs/reference/plugin-reference'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/docs'
    | '/docs/getting-started'
    | '/docs/introduction'
    | '/docs/guides/collections'
    | '/docs/guides/pages'
    | '/docs/reference/frontmatter-reference'
    | '/docs/reference/plugin-reference'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/(prestige)/docs'
    | '/(prestige)/docs/getting-started'
    | '/(prestige)/docs/introduction'
    | '/(prestige)/docs/guides/collections'
    | '/(prestige)/docs/guides/pages'
    | '/(prestige)/docs/reference/frontmatter-reference'
    | '/(prestige)/docs/reference/plugin-reference'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  prestigeDocsLazyRoute: typeof prestigeDocsLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(prestige)/docs': {
      id: '/(prestige)/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof prestigeDocsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(prestige)/docs/introduction': {
      id: '/(prestige)/docs/introduction'
      path: '/introduction'
      fullPath: '/docs/introduction'
      preLoaderRoute: typeof prestigeDocsIntroductionRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/getting-started': {
      id: '/(prestige)/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof prestigeDocsGettingStartedRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/reference/plugin-reference': {
      id: '/(prestige)/docs/reference/plugin-reference'
      path: '/reference/plugin-reference'
      fullPath: '/docs/reference/plugin-reference'
      preLoaderRoute: typeof prestigeDocsReferencePluginReferenceRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/reference/frontmatter-reference': {
      id: '/(prestige)/docs/reference/frontmatter-reference'
      path: '/reference/frontmatter-reference'
      fullPath: '/docs/reference/frontmatter-reference'
      preLoaderRoute: typeof prestigeDocsReferenceFrontmatterReferenceRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/guides/pages': {
      id: '/(prestige)/docs/guides/pages'
      path: '/guides/pages'
      fullPath: '/docs/guides/pages'
      preLoaderRoute: typeof prestigeDocsGuidesPagesRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/guides/collections': {
      id: '/(prestige)/docs/guides/collections'
      path: '/guides/collections'
      fullPath: '/docs/guides/collections'
      preLoaderRoute: typeof prestigeDocsGuidesCollectionsRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
  }
}

interface prestigeDocsLazyRouteChildren {
  prestigeDocsGettingStartedRoute: typeof prestigeDocsGettingStartedRoute
  prestigeDocsIntroductionRoute: typeof prestigeDocsIntroductionRoute
  prestigeDocsGuidesCollectionsRoute: typeof prestigeDocsGuidesCollectionsRoute
  prestigeDocsGuidesPagesRoute: typeof prestigeDocsGuidesPagesRoute
  prestigeDocsReferenceFrontmatterReferenceRoute: typeof prestigeDocsReferenceFrontmatterReferenceRoute
  prestigeDocsReferencePluginReferenceRoute: typeof prestigeDocsReferencePluginReferenceRoute
}

const prestigeDocsLazyRouteChildren: prestigeDocsLazyRouteChildren = {
  prestigeDocsGettingStartedRoute: prestigeDocsGettingStartedRoute,
  prestigeDocsIntroductionRoute: prestigeDocsIntroductionRoute,
  prestigeDocsGuidesCollectionsRoute: prestigeDocsGuidesCollectionsRoute,
  prestigeDocsGuidesPagesRoute: prestigeDocsGuidesPagesRoute,
  prestigeDocsReferenceFrontmatterReferenceRoute:
    prestigeDocsReferenceFrontmatterReferenceRoute,
  prestigeDocsReferencePluginReferenceRoute:
    prestigeDocsReferencePluginReferenceRoute,
}

const prestigeDocsLazyRouteWithChildren =
  prestigeDocsLazyRoute._addFileChildren(prestigeDocsLazyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  prestigeDocsLazyRoute: prestigeDocsLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
