/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as prestigeDocsVitePluginRouteImport } from './routes/(prestige)/docs.vite-plugin'
import { Route as prestigeDocsTypescriptRouteImport } from './routes/(prestige)/docs.typescript'
import { Route as prestigeDocsThemerRouteImport } from './routes/(prestige)/docs.themer'
import { Route as prestigeDocsShowcaseRouteImport } from './routes/(prestige)/docs.showcase'
import { Route as prestigeDocsIntroductionRouteImport } from './routes/(prestige)/docs.introduction'
import { Route as prestigeDocsInstallationRouteImport } from './routes/(prestige)/docs.installation'
import { Route as prestigeApiPrestigeRouteImport } from './routes/(prestige)/api.prestige'
import { Route as prestigeDocsLoadersCustomLoaderRouteImport } from './routes/(prestige)/docs.loaders.custom-loader'
import { Route as prestigeDocsLoadersCloudinaryRouteImport } from './routes/(prestige)/docs.loaders.cloudinary'
import { Route as prestigeDocsLoadersLoaderRouteImport } from './routes/(prestige).docs.loaders.$loader'
import { Route as prestigeDocsImageLoadersOverviewRouteImport } from './routes/(prestige)/docs.image.loaders.overview'

const prestigeDocsLazyRouteImport = createFileRoute('/(prestige)/docs')()
const prestigeApiLazyRouteImport = createFileRoute('/(prestige)/api')()

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const prestigeDocsLazyRoute = prestigeDocsLazyRouteImport
  .update({
    id: '/(prestige)/docs',
    path: '/docs',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(prestige)/docs.lazy').then((d) => d.Route))
const prestigeApiLazyRoute = prestigeApiLazyRouteImport
  .update({
    id: '/(prestige)/api',
    path: '/api',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(prestige)/api.lazy').then((d) => d.Route))
const prestigeDocsVitePluginRoute = prestigeDocsVitePluginRouteImport
  .update({
    id: '/vite-plugin',
    path: '/vite-plugin',
    getParentRoute: () => prestigeDocsLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/docs.vite-plugin.lazy').then((d) => d.Route),
  )
const prestigeDocsTypescriptRoute = prestigeDocsTypescriptRouteImport
  .update({
    id: '/typescript',
    path: '/typescript',
    getParentRoute: () => prestigeDocsLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/docs.typescript.lazy').then((d) => d.Route),
  )
const prestigeDocsThemerRoute = prestigeDocsThemerRouteImport
  .update({
    id: '/themer',
    path: '/themer',
    getParentRoute: () => prestigeDocsLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/docs.themer.lazy').then((d) => d.Route),
  )
const prestigeDocsShowcaseRoute = prestigeDocsShowcaseRouteImport
  .update({
    id: '/showcase',
    path: '/showcase',
    getParentRoute: () => prestigeDocsLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/docs.showcase.lazy').then((d) => d.Route),
  )
const prestigeDocsIntroductionRoute = prestigeDocsIntroductionRouteImport
  .update({
    id: '/introduction',
    path: '/introduction',
    getParentRoute: () => prestigeDocsLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/docs.introduction.lazy').then((d) => d.Route),
  )
const prestigeDocsInstallationRoute = prestigeDocsInstallationRouteImport
  .update({
    id: '/installation',
    path: '/installation',
    getParentRoute: () => prestigeDocsLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/docs.installation.lazy').then((d) => d.Route),
  )
const prestigeApiPrestigeRoute = prestigeApiPrestigeRouteImport
  .update({
    id: '/prestige',
    path: '/prestige',
    getParentRoute: () => prestigeApiLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/api.prestige.lazy').then((d) => d.Route),
  )
const prestigeDocsLoadersCustomLoaderRoute =
  prestigeDocsLoadersCustomLoaderRouteImport
    .update({
      id: '/loaders/custom-loader',
      path: '/loaders/custom-loader',
      getParentRoute: () => prestigeDocsLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/docs.loaders.custom-loader.lazy').then(
        (d) => d.Route,
      ),
    )
const prestigeDocsLoadersCloudinaryRoute =
  prestigeDocsLoadersCloudinaryRouteImport
    .update({
      id: '/loaders/cloudinary',
      path: '/loaders/cloudinary',
      getParentRoute: () => prestigeDocsLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/docs.loaders.cloudinary.lazy').then(
        (d) => d.Route,
      ),
    )
const prestigeDocsLoadersLoaderRoute =
  prestigeDocsLoadersLoaderRouteImport.update({
    id: '/loaders/$loader',
    path: '/loaders/$loader',
    getParentRoute: () => prestigeDocsLazyRoute,
  } as any)
const prestigeDocsImageLoadersOverviewRoute =
  prestigeDocsImageLoadersOverviewRouteImport
    .update({
      id: '/image/loaders/overview',
      path: '/image/loaders/overview',
      getParentRoute: () => prestigeDocsLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/docs.image.loaders.overview.lazy').then(
        (d) => d.Route,
      ),
    )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/test': typeof TestRoute
  '/api': typeof prestigeApiLazyRouteWithChildren
  '/docs': typeof prestigeDocsLazyRouteWithChildren
  '/api/prestige': typeof prestigeApiPrestigeRoute
  '/docs/installation': typeof prestigeDocsInstallationRoute
  '/docs/introduction': typeof prestigeDocsIntroductionRoute
  '/docs/showcase': typeof prestigeDocsShowcaseRoute
  '/docs/themer': typeof prestigeDocsThemerRoute
  '/docs/typescript': typeof prestigeDocsTypescriptRoute
  '/docs/vite-plugin': typeof prestigeDocsVitePluginRoute
  '/docs/loaders/$loader': typeof prestigeDocsLoadersLoaderRoute
  '/docs/loaders/cloudinary': typeof prestigeDocsLoadersCloudinaryRoute
  '/docs/loaders/custom-loader': typeof prestigeDocsLoadersCustomLoaderRoute
  '/docs/image/loaders/overview': typeof prestigeDocsImageLoadersOverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/test': typeof TestRoute
  '/api': typeof prestigeApiLazyRouteWithChildren
  '/docs': typeof prestigeDocsLazyRouteWithChildren
  '/api/prestige': typeof prestigeApiPrestigeRoute
  '/docs/installation': typeof prestigeDocsInstallationRoute
  '/docs/introduction': typeof prestigeDocsIntroductionRoute
  '/docs/showcase': typeof prestigeDocsShowcaseRoute
  '/docs/themer': typeof prestigeDocsThemerRoute
  '/docs/typescript': typeof prestigeDocsTypescriptRoute
  '/docs/vite-plugin': typeof prestigeDocsVitePluginRoute
  '/docs/loaders/$loader': typeof prestigeDocsLoadersLoaderRoute
  '/docs/loaders/cloudinary': typeof prestigeDocsLoadersCloudinaryRoute
  '/docs/loaders/custom-loader': typeof prestigeDocsLoadersCustomLoaderRoute
  '/docs/image/loaders/overview': typeof prestigeDocsImageLoadersOverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/test': typeof TestRoute
  '/(prestige)/api': typeof prestigeApiLazyRouteWithChildren
  '/(prestige)/docs': typeof prestigeDocsLazyRouteWithChildren
  '/(prestige)/api/prestige': typeof prestigeApiPrestigeRoute
  '/(prestige)/docs/installation': typeof prestigeDocsInstallationRoute
  '/(prestige)/docs/introduction': typeof prestigeDocsIntroductionRoute
  '/(prestige)/docs/showcase': typeof prestigeDocsShowcaseRoute
  '/(prestige)/docs/themer': typeof prestigeDocsThemerRoute
  '/(prestige)/docs/typescript': typeof prestigeDocsTypescriptRoute
  '/(prestige)/docs/vite-plugin': typeof prestigeDocsVitePluginRoute
  '/(prestige)/docs/loaders/$loader': typeof prestigeDocsLoadersLoaderRoute
  '/(prestige)/docs/loaders/cloudinary': typeof prestigeDocsLoadersCloudinaryRoute
  '/(prestige)/docs/loaders/custom-loader': typeof prestigeDocsLoadersCustomLoaderRoute
  '/(prestige)/docs/image/loaders/overview': typeof prestigeDocsImageLoadersOverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/test'
    | '/api'
    | '/docs'
    | '/api/prestige'
    | '/docs/installation'
    | '/docs/introduction'
    | '/docs/showcase'
    | '/docs/themer'
    | '/docs/typescript'
    | '/docs/vite-plugin'
    | '/docs/loaders/$loader'
    | '/docs/loaders/cloudinary'
    | '/docs/loaders/custom-loader'
    | '/docs/image/loaders/overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/test'
    | '/api'
    | '/docs'
    | '/api/prestige'
    | '/docs/installation'
    | '/docs/introduction'
    | '/docs/showcase'
    | '/docs/themer'
    | '/docs/typescript'
    | '/docs/vite-plugin'
    | '/docs/loaders/$loader'
    | '/docs/loaders/cloudinary'
    | '/docs/loaders/custom-loader'
    | '/docs/image/loaders/overview'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/test'
    | '/(prestige)/api'
    | '/(prestige)/docs'
    | '/(prestige)/api/prestige'
    | '/(prestige)/docs/installation'
    | '/(prestige)/docs/introduction'
    | '/(prestige)/docs/showcase'
    | '/(prestige)/docs/themer'
    | '/(prestige)/docs/typescript'
    | '/(prestige)/docs/vite-plugin'
    | '/(prestige)/docs/loaders/$loader'
    | '/(prestige)/docs/loaders/cloudinary'
    | '/(prestige)/docs/loaders/custom-loader'
    | '/(prestige)/docs/image/loaders/overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  TestRoute: typeof TestRoute
  prestigeApiLazyRoute: typeof prestigeApiLazyRouteWithChildren
  prestigeDocsLazyRoute: typeof prestigeDocsLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(prestige)/docs': {
      id: '/(prestige)/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof prestigeDocsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(prestige)/api': {
      id: '/(prestige)/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof prestigeApiLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(prestige)/docs/vite-plugin': {
      id: '/(prestige)/docs/vite-plugin'
      path: '/vite-plugin'
      fullPath: '/docs/vite-plugin'
      preLoaderRoute: typeof prestigeDocsVitePluginRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/typescript': {
      id: '/(prestige)/docs/typescript'
      path: '/typescript'
      fullPath: '/docs/typescript'
      preLoaderRoute: typeof prestigeDocsTypescriptRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/themer': {
      id: '/(prestige)/docs/themer'
      path: '/themer'
      fullPath: '/docs/themer'
      preLoaderRoute: typeof prestigeDocsThemerRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/showcase': {
      id: '/(prestige)/docs/showcase'
      path: '/showcase'
      fullPath: '/docs/showcase'
      preLoaderRoute: typeof prestigeDocsShowcaseRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/introduction': {
      id: '/(prestige)/docs/introduction'
      path: '/introduction'
      fullPath: '/docs/introduction'
      preLoaderRoute: typeof prestigeDocsIntroductionRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/installation': {
      id: '/(prestige)/docs/installation'
      path: '/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof prestigeDocsInstallationRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/api/prestige': {
      id: '/(prestige)/api/prestige'
      path: '/prestige'
      fullPath: '/api/prestige'
      preLoaderRoute: typeof prestigeApiPrestigeRouteImport
      parentRoute: typeof prestigeApiLazyRoute
    }
    '/(prestige)/docs/loaders/custom-loader': {
      id: '/(prestige)/docs/loaders/custom-loader'
      path: '/loaders/custom-loader'
      fullPath: '/docs/loaders/custom-loader'
      preLoaderRoute: typeof prestigeDocsLoadersCustomLoaderRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/loaders/cloudinary': {
      id: '/(prestige)/docs/loaders/cloudinary'
      path: '/loaders/cloudinary'
      fullPath: '/docs/loaders/cloudinary'
      preLoaderRoute: typeof prestigeDocsLoadersCloudinaryRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/loaders/$loader': {
      id: '/(prestige)/docs/loaders/$loader'
      path: '/loaders/$loader'
      fullPath: '/docs/loaders/$loader'
      preLoaderRoute: typeof prestigeDocsLoadersLoaderRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/image/loaders/overview': {
      id: '/(prestige)/docs/image/loaders/overview'
      path: '/image/loaders/overview'
      fullPath: '/docs/image/loaders/overview'
      preLoaderRoute: typeof prestigeDocsImageLoadersOverviewRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
  }
}

interface prestigeApiLazyRouteChildren {
  prestigeApiPrestigeRoute: typeof prestigeApiPrestigeRoute
}

const prestigeApiLazyRouteChildren: prestigeApiLazyRouteChildren = {
  prestigeApiPrestigeRoute: prestigeApiPrestigeRoute,
}

const prestigeApiLazyRouteWithChildren = prestigeApiLazyRoute._addFileChildren(
  prestigeApiLazyRouteChildren,
)

interface prestigeDocsLazyRouteChildren {
  prestigeDocsInstallationRoute: typeof prestigeDocsInstallationRoute
  prestigeDocsIntroductionRoute: typeof prestigeDocsIntroductionRoute
  prestigeDocsShowcaseRoute: typeof prestigeDocsShowcaseRoute
  prestigeDocsThemerRoute: typeof prestigeDocsThemerRoute
  prestigeDocsTypescriptRoute: typeof prestigeDocsTypescriptRoute
  prestigeDocsVitePluginRoute: typeof prestigeDocsVitePluginRoute
  prestigeDocsLoadersLoaderRoute: typeof prestigeDocsLoadersLoaderRoute
  prestigeDocsLoadersCloudinaryRoute: typeof prestigeDocsLoadersCloudinaryRoute
  prestigeDocsLoadersCustomLoaderRoute: typeof prestigeDocsLoadersCustomLoaderRoute
  prestigeDocsImageLoadersOverviewRoute: typeof prestigeDocsImageLoadersOverviewRoute
}

const prestigeDocsLazyRouteChildren: prestigeDocsLazyRouteChildren = {
  prestigeDocsInstallationRoute: prestigeDocsInstallationRoute,
  prestigeDocsIntroductionRoute: prestigeDocsIntroductionRoute,
  prestigeDocsShowcaseRoute: prestigeDocsShowcaseRoute,
  prestigeDocsThemerRoute: prestigeDocsThemerRoute,
  prestigeDocsTypescriptRoute: prestigeDocsTypescriptRoute,
  prestigeDocsVitePluginRoute: prestigeDocsVitePluginRoute,
  prestigeDocsLoadersLoaderRoute: prestigeDocsLoadersLoaderRoute,
  prestigeDocsLoadersCloudinaryRoute: prestigeDocsLoadersCloudinaryRoute,
  prestigeDocsLoadersCustomLoaderRoute: prestigeDocsLoadersCustomLoaderRoute,
  prestigeDocsImageLoadersOverviewRoute: prestigeDocsImageLoadersOverviewRoute,
}

const prestigeDocsLazyRouteWithChildren =
  prestigeDocsLazyRoute._addFileChildren(prestigeDocsLazyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  TestRoute: TestRoute,
  prestigeApiLazyRoute: prestigeApiLazyRouteWithChildren,
  prestigeDocsLazyRoute: prestigeDocsLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
