/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as prestigeDocsRouteImport } from './routes/(prestige)/docs'
import { Route as prestigeApiRouteImport } from './routes/(prestige)/api'

const prestigeDocsVitePluginLazyRouteImport = createFileRoute(
  '/(prestige)/docs/vite-plugin',
)()
const prestigeDocsTypescriptLazyRouteImport = createFileRoute(
  '/(prestige)/docs/typescript',
)()
const prestigeDocsIntroductionLazyRouteImport = createFileRoute(
  '/(prestige)/docs/introduction',
)()
const prestigeDocsInstallationLazyRouteImport = createFileRoute(
  '/(prestige)/docs/installation',
)()
const prestigeApiPrestigeLazyRouteImport = createFileRoute(
  '/(prestige)/api/prestige',
)()
const prestigeDocsImageLoadersCustomLoaderLazyRouteImport = createFileRoute(
  '/(prestige)/docs/image/loaders/custom-loader',
)()

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const prestigeDocsRoute = prestigeDocsRouteImport.update({
  id: '/(prestige)/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const prestigeApiRoute = prestigeApiRouteImport.update({
  id: '/(prestige)/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const prestigeDocsVitePluginLazyRoute = prestigeDocsVitePluginLazyRouteImport
  .update({
    id: '/vite-plugin',
    path: '/vite-plugin',
    getParentRoute: () => prestigeDocsRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/docs.vite-plugin.lazy').then((d) => d.Route),
  )
const prestigeDocsTypescriptLazyRoute = prestigeDocsTypescriptLazyRouteImport
  .update({
    id: '/typescript',
    path: '/typescript',
    getParentRoute: () => prestigeDocsRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/docs.typescript.lazy').then((d) => d.Route),
  )
const prestigeDocsIntroductionLazyRoute =
  prestigeDocsIntroductionLazyRouteImport
    .update({
      id: '/introduction',
      path: '/introduction',
      getParentRoute: () => prestigeDocsRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/docs.introduction.lazy').then((d) => d.Route),
    )
const prestigeDocsInstallationLazyRoute =
  prestigeDocsInstallationLazyRouteImport
    .update({
      id: '/installation',
      path: '/installation',
      getParentRoute: () => prestigeDocsRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/docs.installation.lazy').then((d) => d.Route),
    )
const prestigeApiPrestigeLazyRoute = prestigeApiPrestigeLazyRouteImport
  .update({
    id: '/prestige',
    path: '/prestige',
    getParentRoute: () => prestigeApiRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/api.prestige.lazy').then((d) => d.Route),
  )
const prestigeDocsImageLoadersCustomLoaderLazyRoute =
  prestigeDocsImageLoadersCustomLoaderLazyRouteImport
    .update({
      id: '/image/loaders/custom-loader',
      path: '/image/loaders/custom-loader',
      getParentRoute: () => prestigeDocsRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/docs.image.loaders.custom-loader.lazy').then(
        (d) => d.Route,
      ),
    )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api': typeof prestigeApiRouteWithChildren
  '/docs': typeof prestigeDocsRouteWithChildren
  '/api/prestige': typeof prestigeApiPrestigeLazyRoute
  '/docs/installation': typeof prestigeDocsInstallationLazyRoute
  '/docs/introduction': typeof prestigeDocsIntroductionLazyRoute
  '/docs/typescript': typeof prestigeDocsTypescriptLazyRoute
  '/docs/vite-plugin': typeof prestigeDocsVitePluginLazyRoute
  '/docs/image/loaders/custom-loader': typeof prestigeDocsImageLoadersCustomLoaderLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api': typeof prestigeApiRouteWithChildren
  '/docs': typeof prestigeDocsRouteWithChildren
  '/api/prestige': typeof prestigeApiPrestigeLazyRoute
  '/docs/installation': typeof prestigeDocsInstallationLazyRoute
  '/docs/introduction': typeof prestigeDocsIntroductionLazyRoute
  '/docs/typescript': typeof prestigeDocsTypescriptLazyRoute
  '/docs/vite-plugin': typeof prestigeDocsVitePluginLazyRoute
  '/docs/image/loaders/custom-loader': typeof prestigeDocsImageLoadersCustomLoaderLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/(prestige)/api': typeof prestigeApiRouteWithChildren
  '/(prestige)/docs': typeof prestigeDocsRouteWithChildren
  '/(prestige)/api/prestige': typeof prestigeApiPrestigeLazyRoute
  '/(prestige)/docs/installation': typeof prestigeDocsInstallationLazyRoute
  '/(prestige)/docs/introduction': typeof prestigeDocsIntroductionLazyRoute
  '/(prestige)/docs/typescript': typeof prestigeDocsTypescriptLazyRoute
  '/(prestige)/docs/vite-plugin': typeof prestigeDocsVitePluginLazyRoute
  '/(prestige)/docs/image/loaders/custom-loader': typeof prestigeDocsImageLoadersCustomLoaderLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api'
    | '/docs'
    | '/api/prestige'
    | '/docs/installation'
    | '/docs/introduction'
    | '/docs/typescript'
    | '/docs/vite-plugin'
    | '/docs/image/loaders/custom-loader'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api'
    | '/docs'
    | '/api/prestige'
    | '/docs/installation'
    | '/docs/introduction'
    | '/docs/typescript'
    | '/docs/vite-plugin'
    | '/docs/image/loaders/custom-loader'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/(prestige)/api'
    | '/(prestige)/docs'
    | '/(prestige)/api/prestige'
    | '/(prestige)/docs/installation'
    | '/(prestige)/docs/introduction'
    | '/(prestige)/docs/typescript'
    | '/(prestige)/docs/vite-plugin'
    | '/(prestige)/docs/image/loaders/custom-loader'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  prestigeApiRoute: typeof prestigeApiRouteWithChildren
  prestigeDocsRoute: typeof prestigeDocsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(prestige)/docs': {
      id: '/(prestige)/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof prestigeDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(prestige)/api': {
      id: '/(prestige)/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof prestigeApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(prestige)/docs/vite-plugin': {
      id: '/(prestige)/docs/vite-plugin'
      path: '/vite-plugin'
      fullPath: '/docs/vite-plugin'
      preLoaderRoute: typeof prestigeDocsVitePluginLazyRouteImport
      parentRoute: typeof prestigeDocsRoute
    }
    '/(prestige)/docs/typescript': {
      id: '/(prestige)/docs/typescript'
      path: '/typescript'
      fullPath: '/docs/typescript'
      preLoaderRoute: typeof prestigeDocsTypescriptLazyRouteImport
      parentRoute: typeof prestigeDocsRoute
    }
    '/(prestige)/docs/introduction': {
      id: '/(prestige)/docs/introduction'
      path: '/introduction'
      fullPath: '/docs/introduction'
      preLoaderRoute: typeof prestigeDocsIntroductionLazyRouteImport
      parentRoute: typeof prestigeDocsRoute
    }
    '/(prestige)/docs/installation': {
      id: '/(prestige)/docs/installation'
      path: '/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof prestigeDocsInstallationLazyRouteImport
      parentRoute: typeof prestigeDocsRoute
    }
    '/(prestige)/api/prestige': {
      id: '/(prestige)/api/prestige'
      path: '/prestige'
      fullPath: '/api/prestige'
      preLoaderRoute: typeof prestigeApiPrestigeLazyRouteImport
      parentRoute: typeof prestigeApiRoute
    }
    '/(prestige)/docs/image/loaders/custom-loader': {
      id: '/(prestige)/docs/image/loaders/custom-loader'
      path: '/image/loaders/custom-loader'
      fullPath: '/docs/image/loaders/custom-loader'
      preLoaderRoute: typeof prestigeDocsImageLoadersCustomLoaderLazyRouteImport
      parentRoute: typeof prestigeDocsRoute
    }
  }
}

interface prestigeApiRouteChildren {
  prestigeApiPrestigeLazyRoute: typeof prestigeApiPrestigeLazyRoute
}

const prestigeApiRouteChildren: prestigeApiRouteChildren = {
  prestigeApiPrestigeLazyRoute: prestigeApiPrestigeLazyRoute,
}

const prestigeApiRouteWithChildren = prestigeApiRoute._addFileChildren(
  prestigeApiRouteChildren,
)

interface prestigeDocsRouteChildren {
  prestigeDocsInstallationLazyRoute: typeof prestigeDocsInstallationLazyRoute
  prestigeDocsIntroductionLazyRoute: typeof prestigeDocsIntroductionLazyRoute
  prestigeDocsTypescriptLazyRoute: typeof prestigeDocsTypescriptLazyRoute
  prestigeDocsVitePluginLazyRoute: typeof prestigeDocsVitePluginLazyRoute
  prestigeDocsImageLoadersCustomLoaderLazyRoute: typeof prestigeDocsImageLoadersCustomLoaderLazyRoute
}

const prestigeDocsRouteChildren: prestigeDocsRouteChildren = {
  prestigeDocsInstallationLazyRoute: prestigeDocsInstallationLazyRoute,
  prestigeDocsIntroductionLazyRoute: prestigeDocsIntroductionLazyRoute,
  prestigeDocsTypescriptLazyRoute: prestigeDocsTypescriptLazyRoute,
  prestigeDocsVitePluginLazyRoute: prestigeDocsVitePluginLazyRoute,
  prestigeDocsImageLoadersCustomLoaderLazyRoute:
    prestigeDocsImageLoadersCustomLoaderLazyRoute,
}

const prestigeDocsRouteWithChildren = prestigeDocsRoute._addFileChildren(
  prestigeDocsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  prestigeApiRoute: prestigeApiRouteWithChildren,
  prestigeDocsRoute: prestigeDocsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
