/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const prestigeDocsLazyRouteImport = createFileRoute('/(prestige)/docs')()
const prestigeDemoLazyRouteImport = createFileRoute('/(prestige)/demo')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const prestigeDocsLazyRoute = prestigeDocsLazyRouteImport
  .update({
    id: '/(prestige)/docs',
    path: '/docs',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(prestige)/docs.lazy').then((d) => d.Route))
const prestigeDemoLazyRoute = prestigeDemoLazyRouteImport
  .update({
    id: '/(prestige)/demo',
    path: '/demo',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(prestige)/demo.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof prestigeDemoLazyRoute
  '/docs': typeof prestigeDocsLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof prestigeDemoLazyRoute
  '/docs': typeof prestigeDocsLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(prestige)/demo': typeof prestigeDemoLazyRoute
  '/(prestige)/docs': typeof prestigeDocsLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo' | '/docs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo' | '/docs'
  id: '__root__' | '/' | '/(prestige)/demo' | '/(prestige)/docs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  prestigeDemoLazyRoute: typeof prestigeDemoLazyRoute
  prestigeDocsLazyRoute: typeof prestigeDocsLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(prestige)/docs': {
      id: '/(prestige)/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof prestigeDocsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(prestige)/demo': {
      id: '/(prestige)/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof prestigeDemoLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  prestigeDemoLazyRoute: prestigeDemoLazyRoute,
  prestigeDocsLazyRoute: prestigeDocsLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
