on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          # Automatically provided by GitHub Actions to create PRs/Tags
          token: ${{ secrets.GITHUB_TOKEN }}
          # Use manifest/config to control package path and name
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
